// Your app constants here!
const ALLOWED_MIME_TYPES = {
    'image/png': 'png',
    'image/jpg': 'jpg',
    'image/jpeg': 'jpeg',
    'image/gif': 'gif',
    'image/svg+xml': 'svg',
    'image/x-icon': 'ico',
    'image/tiff': 'tiff',
    'application/vnd.ms-excel': 'xls',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'xlsx',
    'text/csv': 'csv',
    'text/html': 'html',
    'application/msword': 'doc',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
    'text/plain': 'txt',
    'application/pdf': 'pdf',
    'application/zip': 'zip',
    'font/ttf': 'ttf',
    'application/vnd.ms-fontobject': 'eot',
    'font/woff': 'woff',
    'font/woff2': 'woff2',
    'application/x-pkcs12': 'p12',
    'application/pkix-cert': 'crt',
    'application/x-x509-ca-cert': 'crt',
    'application/x-x509-user-cert': 'crt',
}
module.exports = ALLOWED_MIME_TYPES