openapi: 3.0.0
info:
  description: "DomClick dev api"
  version: 1.0.0
  title: "DomClick dev"
  termsOfService: "http://osipuk.ru/"
  contact:
    email: "andrey.o@list.ru"
tags:
- name: "users"
  description: "Access users"
  externalDocs:
    description: ""
    url: "http://"
- name: "flats"
  description: "Access to flats"

paths:
  /users:
    get:
      tags:
      - "users"
      summary: "Get all users"
      description: "get users"
      operationId: "get users"
      parameters:
        - in: query
          name: "body"
          description: "Get all users"
          required: true
          schema:
            $ref: "#/components/schemas/Users"
      responses:
        "204":
          description: 'An error has occurred'
    post:
      tags:
      - "users"
      summary: "Put new user"
      description: "Put new user"
      operationId: "Put new user"
      parameters:
        - in: query
          name: user
          description: New user
          required: true
          schema:
            $ref: "#/components/schemas/Users"
      responses:
        "204":
          description: 'An error has occurred'
    put:
      tags:
      - "users"
      summary: "Update user"
      operationId: "Update user"
      description: "Update user"
      parameters:
        - in: query
          name: user
          description: New user
          required: true
          schema:
            $ref: "#/components/schemas/Users"
      responses:
        "204":
          description: 'An error has occurred'
  /users/{id}:
    get:
      tags:
      - "users"
      summary: "Get one users"
      description: "get one user"
      operationId: "get one user"
      parameters:
        - name: id
          in: path
          description: "get one user"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: 'An error has occurred'
    delete:
      tags:
      - "users"
      summary: "Delete one user"
      description: "Delete one user"
      operationId: "Delete one user"
      parameters:
        - name: id
          in: path
          description: "Delete one user "
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "204":
          description: 'An error has occurred'
  /flats:
    get:
      tags:
      - flats
      summary: Get all flats
      description: get flats
      operationId: get flats
      parameters:
      - name: page
        in: query
        description: default page 1
        schema:
          type: string
          example: 1, 2, 3
      - name: limit
        in: query
        description: default limit 10
        schema:
          type: string
          example: 10, 20, 30
      responses:
        204:
          description: An error has occurred
    post:
      tags:
      - "flats"
      summary: "Put new flat"
      description: "Put new flat"
      operationId: "Put new flat"
      parameters:
        - in: "query"
          name: "body"
          description: "Put new flat"
          required: true
          schema:
            $ref: "#/components/schemas/Flats"
      responses:
        204:
          description: An error has occurred
  /flats/{id}:
    get:
      tags:
      - "flats"
      summary: "Get one flat"
      description: "Get one flat"
      operationId: "Get one flat"
      parameters:
        - name: id
          in: path
          description: ID of flats to return 
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Flats'
        "204":
          description: 'An error has occurred'
    put:
      tags:
      - "flats"
      summary: "Update flat"
      description: "Update flat"
      operationId: "Update flat"
      parameters:
        - name: id
          in: path
          description: ID of flats to return 
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: An error has occurred
    patch:
      tags:
      - "flats"
      summary: "В разработке"
      description: "В разработке"
      operationId: "В разработке"
      parameters:
        - name: id
          in: path
          description: ID of flats to return 
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: An error has occurred
    delete:
      tags:
      - "flats"
      summary: Удалить объект
      description: Удалить объект
      operationId: Удалить объект
      parameters:
        - name: id
          in: path
          description: ID of flats to return 
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        204:
          description: An error has occurred
  /auth/signin:
    post:
      tags:
      - "auth"
      summary: Авторизация
      description: Авторизация
      operationId: Авторизация
      parameters:
        - name: login
          in: query
          description: login
          required: true
          schema:
            type: string
            format: string
        - name: password
          in: query
          description: password encode base64
          required: true
          schema:
            type: string
            format: string
      responses:
        204:
          description: An error has occurred
  /auth/register:
    post:
        tags:
        - "auth"
        summary: Регистрация
        description: Регистрация
        operationId: Регистрация
        parameters:
          - name: login
            in: query
            description: login
            required: true
            schema:
              type: string
              format: string
          - name: password
            in: query
            description: password
            required: true
            schema:
              type: string
              format: string
          - name: role
            in: query
            description: role
            required: true
            schema:
              type: string
              format: string
        responses:
          204:
            description: An error has occurred
  /auth/logout:
    post:
        tags:
        - "auth"
        summary: Logout
        description: Logout
        operationId: Logout
        parameters:
          - name: user
            in: query
            description: login
            required: true
            schema:
              type: string
              format: string
        responses:
          204:
            description: An error has occurred
    
components:
  schemas:
    Users:
      type: "object"
      required:
      - "name"
      - "password"
      - "role"
      properties:
        id:
          type: "string"
          format: "ObjectID"
        name:
          type: "string"
          format: "string"
        password:
          type: "string"
          format: "string"
        role:
          type: "string"
          description: "Role"
          enum:
          - "admin"
          - "user"
    Flats:
      type: "object"
      required:
      - owner
      - documents
      - cadastral_value
      - address
      - deal
      - terms_of_sale
      - additionally
      - house
      - flat
      properties:
        id:
          type: "string"
          format: "ObjectID"
        owner:
          type: "string"
        documents:
          type: "array"
          items:
            type: "string"
        cadastral_value:
          type: "object"
          required:
          - value
          properties:
            value:
              type: "string"
            comment:
              type: "string"
        address:
          type: "object"
          required:
          - value
          properties:
            value:
              type: "string"
            comment:
              type: "string"
        deal:
          type: object
          required:
            - type_deal
            - property_type
            - type_of_property
            - years_in_ownership
            - number_of_owners
            - registered
          properties:
            comment:
              type: "string"  
            type_deal:
              type: "string" 
              enum:
              - "Продажа"
              - "Аренда"
            property_type:
              type: "string"
              enum:
              - "Жилая"
              - "Коммерческая"  
              - "Гараж"  
            type_of_property:
              type: "string"
              enum:
              - "Квартира"
              - "Комната"  
              - "Дом"  
              - "Таунхаус"  
              - "Часть дома"  
              - "Участок"  
            years_in_ownership:
              type: "string"
              enum:
              - "Меньше 3-х"
              - "От 3-х до 5-ти"  
              - "Больше 5-ти"  
            number_of_owners:
              type: "object"
              required:
              - value
              properties:  
                value:
                  type: "string"
                  enum:
                  - "1"
                  - "2"  
                  - "3+"
                minor_child:
                  type: "boolean"
                  default: false
            registered:
              type: "object"
              required:
              - value
              properties:  
                value:
                  type: "string"
                  enum:
                  - "1"
                  - "2"  
                  - "3+"
                minor_child:
                  type: "boolean"
                  default: false
        terms_of_sale:
          type: "object"
          required:
          - cost
          - gas
          - refuse_chute
          properties:
            comment:
              type: "string"
            cost: 
              type: "object"
              required:
              - value
              properties:
                value:
                  type: "number"
                trade:
                  
                  type: "boolean"
                  default: false
            gas:
              type: "boolean"
            refuse_chute:
              type: "boolean"
        additionally:
          type: "object"
          required:
          - security
          - parking
          - the_landscaping_of_the_yard
          - infrastructure
          - bathroom
          - balcony
          - repair
          - view_from_windows
          properties:
            security: 
              type: "object"
              required:
              - doorphone
              - concierge
              - code_door
              - closed_territory
              properties:
                comment:
                  type: "string"
                doorphone:
                  type: "boolean"
                  default: false
                concierge:
                  type: "boolean"
                  default: false
                code_door:
                  type: "boolean"
                  default: false
                closed_territory:
                  type: "boolean"
                  default: false
            parking:
              type: "object"
              required:
              - in_the_courtyard
              - underground
              - barrier
              - garage
              - security
              properties:
                comment:
                  type: "string"
                in_the_courtyard:
                  type: "boolean"
                  default: false
                underground:
                  type: "boolean"
                  default: false
                barrier:
                  type: "boolean"
                  default: false
                garage:
                  type: "boolean"
                  default: false
                security:
                  type: "boolean"
                  default: false
            the_landscaping_of_the_yard:
              type: "object"
              required:
              - childrens_playground
              - sports_ground
              properties:
                comment:
                  type: "string"
                childrens_playground:
                  type: "boolean"
                  default: false
                sports_ground:
                  type: "boolean"
                  default: false
            infrastructure:
              type: "object"
              required:
              - school
              - fitness
              - park
              - kindergarten
              - mall
              properties:
                comment:
                  type: "string"
                school:
                  type: "boolean"
                  default: false
                fitness:
                  type: "boolean"
                  default: false
                park:
                  type: "boolean"
                  default: false
                kindergarten:
                  type: "boolean"
                  default: false
                mall:
                  type: "boolean"
                  default: false
            bathroom:
              type: "object"
              required:
              - value
              properties:
                comment:
                  type: "string"
                value:
                  type: "string"
                  enum:
                  - "Совмещенный"
                  - "Раздельный"  
                  - "Более одного" 
            balcony:
              type: "object"
              required:
              - value
              properties:
                comment:
                  type: "string"
                value:
                  type: "string"
                  enum:
                  - "1"
                  - "2"  
                  - "3+" 
                  - "Нет" 
            repair:
              type: "object"
              required:
              - value
              properties:
                comment:
                  type: "string"
                value:
                  type: "string"
                  enum:
                  - "Косметический"
                  - "Евро"  
                  - "Дизайнерский" 
                  - "Без ремонта" 
            view_from_windows:
              type: "object"
              required:
              - yard
              - street
              - park
              - reservoir
              - forest
              properties:
                comment:
                  type: "string"
                yard:
                  type: "boolean"
                  default: false
                street:
                  type: "boolean"
                  default: false
                park:
                  type: "boolean"
                  default: false
                reservoir:
                  type: "boolean"
                  default: false
                forest:
                  type: "boolean"
                  default: false
        house:
          type: "object"
          required:
          - type
          - elevator
          - apartment_number
          - foto
          - video
          properties:
            comment:
              type: "string"
            security:
              type: "string"
            type:
              type: "string"
              enum: 
              - Кирпичный
              - Панельный
              - Монолитный
              - Деревянный
              - Блочный
            elevator:
              type: object
              required: 
              - value
              - freight_elevator
              properties:
                value:
                  type: string
                  enum: 
                  - "1"
                  - "2"
                  - "3+"
                freight_elevator:
                  type: boolean
                  default: false
            apartment_number:
              type: number
            cadastral_number:
              type: number
            foto:
              type: object
              required: 
              - value
              properties:
                comment:
                  type: string
                value:
                  type: array
                  items:
                    type: string
            video:
              type: object
              required: 
              - value
              properties:
                comment:
                  type: string
                value:
                  type: array
                  items:
                    type: string
        flat:
          type: object
          required: 
          - rooms
          - freight_elevator
          - square
          - square_kitchen
          - square_residential
          - floor
          - floors_in_the_house
          - ceiling_height
          properties:
            comment:
              type: string
            rooms:
              type: string
              enum: 
              - "1"
              - "2"
              - "3"
              - "4"
              - "5+"
              - "Студия"
            freight_elevator:
              type: boolean
              default: false
            square:
              type: boolean
              default: false
            square_kitchen:
              type: boolean
              default: false
            square_residential:
              type: boolean
              default: false
            floor:
              type: boolean
              default: false
            floors_in_the_house:
              type: boolean
              default: false
            ceiling_height:
              type: boolean
              default: false
# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DomClick7/Domclick/1.0.0