//
// Flats.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Flats: Codable {

    public enum Currency: String, Codable { 
        case p = "P"
        case dollar = "$"
        case gr = "Gr"
    }
    public var _id: String?
    public var images: [Flats]?
    public var cost: Int?
    public var costM2: Int?
    /** Currency */
    public var currency: Currency?
    public var owner: String?
    public var rooms: Int?
    public var floor: Int?
    public var city: String?
    public var address: String?
    public var area: String?

    public init(_id: String?, images: [Flats]?, cost: Int?, costM2: Int?, currency: Currency?, owner: String?, rooms: Int?, floor: Int?, city: String?, address: String?, area: String?) {
        self._id = _id
        self.images = images
        self.cost = cost
        self.costM2 = costM2
        self.currency = currency
        self.owner = owner
        self.rooms = rooms
        self.floor = floor
        self.city = city
        self.address = address
        self.area = area
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case images
        case cost
        case costM2 = "cost_m2"
        case currency
        case owner
        case rooms
        case floor
        case city
        case address
        case area
    }


}

