//
// Users.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Users: Codable {

    public enum Role: String, Codable { 
        case admin = "admin"
        case user = "user"
    }
    public var _id: String?
    public var name: String
    public var password: String
    /** Role */
    public var role: Role

    public init(_id: String?, name: String, password: String, role: Role) {
        self._id = _id
        self.name = name
        self.password = password
        self.role = role
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case password
        case role
    }


}

